server:
  port: 8093

spring:
  application:
    name: zuul
#设置eureka 注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

  instance:
    prefer-ip-address: true
zuul:
  routes:
    client-a:
      #访问路径
      path: /app-a/**
      #服务注册ID
      serviceId: order
    client-b:
      path: /app-b/**
      serviceId: manage
